name: smart_travel_app
description: A Smart Travel & Reclamation App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  flutter_dotenv: ^5.1.0
  http: ^1.1.0
  sqflite: ^2.3.0
  path: ^1.8.3
  url_launcher: ^6.1.11
  intl: ^0.18.1
  printing: ^5.9.1
  pdf: ^3.10.4
  image_picker: ^1.0.4
  sqflite_common_ffi: ^2.3.2   # ✅ ajouté pour desktop/web support
  # RETIRER sqflite_common_ffi_web - on va gérer web/mobile différemment
  flutter_map: ^7.0.2
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
