name: smart_travel_weather_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.9.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.2.5
  path: ^1.8.3
  path_provider: ^2.0.15
  provider: ^6.0.5
  http: ^0.13.6
  pdf: ^3.11.0
  printing: ^5.10.4
  url_launcher: ^6.1.7   # <- ajouté pour ouvrir email ou PDF

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/smartravel.png
